### ISSUE TITLE
Empty zip is being uploaded

### ISSUE THREAD

**Issue by MicrorealHQ** [arbisyarifudin/wwebjs-aws-s3#3]
Reprocedure: I am currently following your example.
But after running, only empty folder is being uploaded (folder name: Default inside this zip file)
I am running on Windows, Node 18
![image](https://github.com/arbisyarifudin/wwebjs-aws-s3/assets/91735608/a55446a5-2ea1-4f34-aae2-c7c4bf469781)

**Comment by fabiodevn1** [comment]
How did you solve it? I believe I will also get something more suitable here if anyone has the same problem.
